### ISSUE TITLE
Science Sleuth 2016

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#539]
## Config
* [x] Copy SS2015 MoCo campaign, opt-in paths to SS2016
* [x] New SS2016 mData's or edit existing SS2015 mData's (which use query string to id=201)
* [x] Add opt-in-paths to new `donorschoose` document in compose.io
* [x] Set `DONORSCHOOSE_MOCO_CAMPAIGN_ID` and `DONORSCHOOSE_BOT_ID` on prod (#583)

## Code
* [x] Refactor `donorschoose` endpoints to return first project in zip based on sortBy=2 (#545)
* [x] Change hardcoded `PROJECT_CREATION_CUTOFF_DATE` (#545)
* [x] Add debug logging for full Donation flow 
* [x] Add zip code (~~or geolocation~~) into conversation and add to the DonorsChoose API query (#566)
* [x] Staging and Production environments
* [x] Add edge case handling (nice to have) #550 

## Questions
* [x] Why did we use the project creation cutoff date in #545? A: Don't know, but we don't think we need it.
* [x] Do we need to worry about donation funds depleting? (Do we do this in code at all currently? How much $$ was donated in 2014 and 2015?) A: We need to just manually check our donorschoose account for now to keep an eye on things.

**Comment by aaronschachter** [comment]
Added checklist item to change hardcoded `PROJECT_CREATION_CUTOFF_DATE` value, currently set to [October 20th, 2015 12:00:01 AM GMT](https://github.com/DoSomething/ds-mdata-responder/blob/c7da5b0358da2a1ac63aca13a38a706220e1c376/app/lib/donations/controllers/DonorsChooseDonationController.js#L36). Not sure why logic exists in first place, but the code comments suggest it is to [return projects created after that Oct 20 2015 date](https://github.com/DoSomething/ds-mdata-responder/blob/c7da5b0358da2a1ac63aca13a38a706220e1c376/app/lib/donations/controllers/DonorsChooseDonationController.js#L140).

**Comment by aaronschachter** [comment]
Sample texts when [`sendSuccessMessages`](https://github.com/DoSomething/ds-mdata-responder/blob/695e54f1b177ebe6539ab20b2349b217d2dba374/app/lib/donations/controllers/DonorsChooseDonationController.js#L482) executes after a successful DC donation (user gets 3 messages in a row):

![slack for ios upload-4](https://cloud.githubusercontent.com/assets/1236811/17380281/4a79ef62-597b-11e6-8fce-ff96601a733a.jpg)

**Comment by aaronschachter** [comment]
✅ Production Mobile Commons Campaign and mData's have been configured and tested.
