### ISSUE TITLE
Import failed reportbacks into Phoenix

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#544]
Creating issue to track currently unscheduled work to import `ds-mdata-responder.reportbacks` that never made it into Phoenix.  Refs scenario 1 in https://github.com/DoSomething/ds-mdata-responder/issues/506#issuecomment-236208672.

From [#gambit Slack](https://dosomething.slack.com/archives/gambit/p1469568446000064) the `reportbacks` collection in the ds-mdata-responder db, which is all campaign sessions that haven’t completed, has about 16K records total:

Over 10K of those contain photos.
6700 contain photo and caption
2470 contain photo, caption, and `why_important`
506 of those 2470 are from `notesfromshawn2016`

`db.getCollection('reportbacks').find({ photo: { $exists: true }, caption: { $exists: true }, why_important: { $exists: true }, campaign: "notesfromshawn2016" }).count()`
## todo
- [x] Run script to import
- [x] Back-date imported July RBs to 31 July
- [x] Back-date new members with July RB activity to timestamp in `reportbacks` document
- [ ] Delete imported `reportbacks` documents 

cc @mshmsh5000 @classicfreddie @jamjensen

**Comment by mshmsh5000** [comment]
Assigning to myself for now as I have the batch of complete, unsubmitted RBs ready to submit into Phoenix.

**Comment by aaronschachter** [comment]
sounds good @mshmsh5000 ! I added a checklist into the issue description.

**Comment by mshmsh5000** [comment]
I've added tabs to the spreadsheet we're using to track this that break out the list into two groups:

1. Submissions to closed campaigns (139)
2. Submissions by users who don't exist on Thor (1037)

That's 100% of the submissions. The script I'm writing needs to handle user creation to process the vast majority of these. Writing in Python, but I'll take this repo's [userCreate](https://github.com/DoSomething/ds-mdata-responder/blob/dev/app/lib/ds-content-api/index.js#L40) method as inspiration.

Not sharing the script in this repo as some sensitive values are hard-coded.

**Comment by mshmsh5000** [comment]
Completed first item on the checklist last week, and added a new item: **Back-date imported July RBs to 31 July**

Context: We imported all of the RBs via the Phoenix API, so they were dated to when we hit the API (11 Aug). Need to take the RBs that were originally created in July and back-date them properly via DB calls.

**Comment by mshmsh5000** [comment]
All of the data cleanup is done, except for the last task (deleting the original stuck RBs from the `reportbacks` collection). Not sure what our care-meter is for that at this point.

**Comment by mshmsh5000** [comment]
Our care-meter seems to be low.

**Comment by jamjensen** [comment]
@mshmsh5000 I'm importing users that have completed `ask_why` but didn't make it into the MoCo completed campaign for October campaigns. I'm doing this so that Hannah is able to include the "stuck" users when awarding scholarships. This should be the last time, given that we no longer have multiple MoCo campaigns.

**Comment by mshmsh5000** [comment]
👍 👍 🌮
