### ISSUE TITLE
Support Reminder Broadcasts

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#742]
## Tasks
* [x] Add `Broadcast` model
* [x] Refactor Signup Broadcasts to find Campaign based on incoming `broadcast_id` , deprecate `CAMPAIGNBOT_BROADCAST_CAMPAIGN` config variable
* [ ] Add additional check for `broadcast_type` for `reminder` -- If yes response, start/continue Reportback Submission

## Overview

The `chatbot` router currently determines whether an incoming mData request is from a Signup Broadcast by checking for a `req.body.broadcast_id` (#739).

For a Yes response, it will post a Signup to whatever the `CAMPAIGNBOT_BROADCAST_CAMPAIGN` is set for (#718).

This won't work for Reportback Reminder Broadcasts, where we'll be sending multiple Mobile Commons broadcasts for the various CampaignBot Campaigns. We can add support for multiple Mobile Commons Broadcasts by building a new `mobilecommons_broadcasts` collection with fields:

* `broadcast_id`
* `campaign_id`
* `broadcast_type`

When an admin creates a new broadcast in Mobile Commons, they'll need to add the Broadcast ID, the DS Campaign to associate it for, and the broadcast type (`signup` or `reminder`) manually into the `mobilecommons_broadcasts` collection.

When the `chatbot` router receives an mData request containing a `req.body.broadcast_id`, find it in the `mobilecommons_broadcasts` table and take the following action for each `broadcast_type`:

* `signup`
    * Yes response: Signup for the Campaign associated with `broadcast_id`
    * No response: Send CampaignBot `signup_broadcast_declined` message, opt into Agent View

* `reminder`
    * Yes response: Similar to the Reportback start command, either create a new draft and ask for quantity, or continue where member left off in their draft
     * No response: Send new CampaignBot `reminder_broadcast_declined` message, opt into Agent View

cc @jamjensen

**Comment by jamjensen** [comment]
Aaron went on leave right before we made a final decision on how users would respond to Reminder Broadcasts so I went with Papa Roach MVP Last Resort: have members text in campaign keyword.

**Comment by aaronschachter** [comment]
@jamjensen #743 spells out how Reminder Broadcasts + chatbot mData could work per our discussion you and I had either 11/10 or 11/11, and also documents what you just mentioned -- our last resort for reminder messages if we couldn't get Reminder Broadcast mData support in  just asking member to respond with a keyword (no mData support).

**Comment by aaronschachter** [comment]
@deadlybutter @sergii-tkachenko This issue could use an update (or close for a new one) as you're both working on Reminders (same for #743)

**Comment by aaronschachter** [comment]
Closing this out until the work is scheduled.
