### ISSUE TITLE
Option to send support requests to Zendesk instead of Agent View

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#896]
_FEATURE OVERVIEW_
-------------------
#### User Story
As a Member Support staffer, I want to receive and respond to Gambit support requests using Zendesk instead of Agent View.

#### Current Implementation
When a member texts the Member Support Command ("Q"), they are opted into the Chatbot Agent View Opt-in Path. All incoming messages from the User are placed into the Agent View queue.  If the User wants to continue their Gambit Campaign conversation, they must text back the Signup Keyword.

#### TODO
* [ ] When a member texts Member Support Command, their message is posted to the Zendesk API as a new ticket.
* [ ] After the member sends their support question, Gambit responds with a new `member_support_confirmation` message, informing the User their message will be answered by a DoSomething staffer from a different phone number (e.g. _"Thanks for the question, we've created a support ticket and we'll try to text back an answer within 24 hrs. Text BOOKBOT to continue Two Books, or QUESTION if you need to add more info to your ticket."_) 

    * All subsequent incoming messages are answered by Gambit: If the user didn't send a valid Start or Member Support command, Gambit will reply with the a "Sorry, I didn't get that" + the Member Support Confirmation message

* [ ] We need the ability to switch this feature off completely via config variable, to return sending support requests to Agent View 

* [ ] BONUS Filtering: If the support ticket contains any explicit language, don't create the ticket but respond a prompt to reword their question appropriately (#895)

cc @jamjensen @justkika @classicfreddie

**Comment by justkika** [comment]
This looks great! I think the pre-work we'll want to have set up on the Zendesk side is having macros to answer common questions as well as the ticket tagging so that we can autofilter the SMS messages to one zendesk account.

**Comment by justkika** [comment]
Also, context that might be helpful is where this member is messaging from: broadcast, reminder message, etc. Is that something we have the ability to do for an MVP?

**Comment by aaronschachter** [comment]
In exploring Zendesk Text, I found I was able to send replies to a Zendesk ticket via text when the ticket was created via my texting the our Zendesk number directly. Within Zendesk, I was not able to send a text response to a ticket created via Zendesk API (Gambit), the replies from Zendesk would only be sent over email.

I submitted a Zendesk support ticket for guidance, here's their response:
>  I reached out to our Talk/Text team and they said there was no API setup that would allow you to create the ticket via app API and then switch the channel over to text.  However, they recommended modifying the trigger found in[ Sending proactive outbound texts: Recipes and tips to allow you to send a response via SMS](https://support.zendesk.com/hc/en-us/articles/235638348-Sending-proactive-outbound-texts-Recipes-and-tips-Talk-Basic-and-Advanced-).  If the requester responds, it would create a new ticket instead of appending to the original but at least you would be able to send that first response via SMS.

I'll look into this approach and document its pros and cons in our [SMS Spec](https://docs.google.com/a/dosomething.org/document/d/1BfVFLgOuYS1vA3d23sPkabkoDwFs0Ebm1nFlT30nT9E/edit?usp=sharing).

**Comment by aaronschachter** [comment]
More details from a Zendesk support rep below. I'm leaning towards jumping ship on using Zendesk Text for now as it seems workarounds rely on triggers that would open at least 2 Zendesk tickets per support request (when ideally we just want the single ticket)

> This issue we are running into here is that since this is not a supported workflow we are trying to cobble together a workaround.  I think you could set something up that replicates what you are looking to do but it's going to be a little messy.  

> Without setting up the workflow and testing I can't be sure, but I believe what you would need to do is create a trigger similar to "Send automated text responses". You will need to incorporate a unique tag as a condition.  This tag will need to be added during ticket creation for these tickets.  The trigger would then fire to send the automated response to the requester via SMS but this is only a one way message.  If the requester responds to that text, a new ticket will be created and will not have any connection to the previous one other than it being from the same requester.

> This leaves you in an awkward position because if you want to send an SMS response, you'll need to use the "Start a text conversation with proactive outbound texts" trigger and modify to apply to the open ticket.  But there again, if the requester responds, it will create a new ticket.  So for this workflow, you'll be dealing with a minimum of two separate tickets for each request submitted this way.

> Sadly, this is a function of the Text channel being in its infancy and is currently only designed to create tickets from inbound texts.  Expanding this functionality is in development but I do not have have a timeline as to when it will be available. :-/

I hope this helps clarify the situation.  Feel free to reach out if you have any other questions.

Have a great weekend!

**Comment by aaronschachter** [comment]
@hbghidey and I chatted through a way we could implement this today, following the steps described in "Send automated responses":

* When a member texts the Member Support Command, create a Zendesk ticket tagged with something like `gambit_member_support`
* Set up a trigger to send an automated response, send us your question and we'll get back to you asap. This message is sent from a long code (not our shortcode)
* When member submits their question by responding to the message sent from long code, a new Zendesk ticket is created, allowing an agent to respond over text (over the long code)

@hbghidey suggested we create a separate Zendesk instance to avoid interfering with our current workflow for email tickets.

**Comment by aaronschachter** [comment]
Here's example copy of what the start of the Zendesk conversation could look like:

* Member texts Q (member support command) to 38383
* Zendesk sends the first message from our longcode.
*  Member responds with their question via text
* We see their question as a new ticket in Zendesk, respond through Zendesk which gets delivered back as SMS (Puppet Sloth responded to this ticket in particular): 

![image uploaded from ios 5](https://cloud.githubusercontent.com/assets/1236811/26226113/54d70ad4-3bdf-11e7-89d5-ec3093ef0300.jpg)

**Comment by aaronschachter** [comment]
Refs #915, https://www.pivotaltracker.com/n/projects/1979505/stories/145639137
