### ISSUE TITLE
Switch Get/Post Signups & Reportbacks from Phoenix to Rogue

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/gambit#970]
_FEATURE OVERVIEW_
-------------------
#### User Story
As a developer I'd like to post directly to Rogue instead of the Phoenix proxy endpoints to create Signups and Reportbacks, and query the Rogue API for fetching a user's current Signup.

#### Additional Information (optional)
#922 

#### Tasks
* [x] Post Signup to Rogue via https://github.com/DoSomething/rogue/blob/master/documentation/endpoints/signups.md#signups - #974 
* [x] Post Reportback to Rogue via https://github.com/DoSomething/rogue/blob/master/documentation/endpoints/posts.md#create-a-post-and/or-create/Update-a-signup
* [x] Get current Signup from Rogue via https://github.com/DoSomething/rogue/blob/master/documentation/endpoints/activity.md#activity
